name = "UnPack"
uuid = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
authors = ["Mauro Werder"]
version = "1.0.2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
